### ISSUE TITLE
Potential to use native openvpn for site-to-site connections using a hostname?

### ISSUE THREAD

**Issue by pgregg88** [dlk3/openvpn-udm#1]
@dlk3 Thanks for posting this work.
I'm looking for a solution to a different, but related use case.
I have (2) UDM Pros that are both on different dynamic IP addresses. Each resolve to a dynamic DNS host name.

The native UDM Pro only allows for a remote host IP address rather than a host name.

Do you have insight on how your work could be extended to address this issue? Happy to contribute.

**Comment by dlk3** [comment]
Is it really true that the UDM configuration UI will only let you use an IP address and not a hostname?  If that's the case then I think, without having actually tested anything, that you ought to be able to do what you're asking using the same process I am.  All you would have to do is create your own version of the OpenVPN config file (openvpn-server.conf) to define the connection.  You could use the UDM configuration UI to generate a template for the config file if you wanted to, with the IP address in it, and then copy out that file and modify it to use a hostname instead.  I'm thinking that would be the only change in my package you'd have to make but, as I said,  I haven't tested that assumption.

**Comment by pgregg88** [comment]
Yep, It's true. People have been begging them to change it for a couple of years. Hasn't happened. I'm looking forward to checking out your solution. Thanks.
